spring:
  main:
    banner-mode: log
  application:
    name: App
  profiles:
    active: PROD
#    active: DEV
  liquibase:
    change-log: classpath:db/src/changelog.yaml
    enabled: false
    url: ${spring.datasource.url}
    password: ${spring.datasource.password}
    user: ${spring.datasource.username}
  datasource:
    url: postgres://ggoktkxtomizma:f5e9844085514ff9fa07c26533d9de7aa099ad9c54efa32078555932a426565f@ec2-54-75-184-144.eu-west-1.compute.amazonaws.com:5432/dfnffn8bn8u0gi
    password: f5e9844085514ff9fa07c26533d9de7aa099ad9c54efa32078555932a426565f
    username: ggoktkxtomizma

#  thymeleaf:
#    cache: false
#    check-template: true
#    check-template-location: true
#    enabled: true
#    encoding: UTF-8
#    mode: HTML
#    prefix: classpath:/templates/
#    suffix: .html

#  jpa:
#    show-sql: false
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.SQLServer2012Dialect
#  datasource:
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://localhost:1433;databaseName=Users;
##    url: jdbc:jdbc:sqlserver://172.17.0.2:1433;databaseName=Test;
#    username: sa
#    password: SaUser123456

#user:
#  datasource:
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://localhost:1433;databaseName=Users;
#      #    url: jdbc:jdbc:sqlserver://172.17.0.2:1433;databaseName=Test;
#    username: sa
#    password: SaUser123456



